### ISSUE TITLE
React.addons.TestUtils.Simulate.?

### ISSUE THREAD

**Issue by mohanzhang** [zilverline/react-tap-event-plugin#10]
I'm not sure if I'm missing something obvious, but does this work with TestUtils.Simulate? Do I just simulate the onTouchTap using a touchStart and touchEnd, or is this completely different?

The source suggests to me that it works with both touches and clicks, but my tests that were previously using Simulate.click start to fail once I change onClick in the component to onTouchTap. Any ideas?

**Comment by mohanzhang** [comment]
As it turns out (and is usually the case), I was indeed missing something obvious: I had forgotten these two lines in my tests:

```javascript
  injectTapEventPlugin = require("react-tap-event-plugin")
  injectTapEventPlugin()
```

Doing that will make `Simulate.touchTap` available to you, and everything is just dandy after that. Sorry for the false alarm, and thanks @zilverline for this plugin!

**Comment by mrgenixus** [comment]
Awkwardly not finding this to be effective using enzyme.  Bug here? Bug in Enzyme?
