### ISSUE TITLE
Didn't support preact ? Hope to see that preact will be supported

### ISSUE THREAD

**Issue by ApsarasX** [zilverline/react-tap-event-plugin#104]
When I try to use `react-tap-event-plugin` in my preact project,  it reported error that 
```
./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Can't resolve 'react-dom/lib/EventPluginHub' in '/Users/chenwengang/wireless-sign-in/preact-web-sign-in/node_module
s/react-tap-event-plugin/src'
```

maybe you haven't heard [preac](https://preactjs.com/)t, it's` Fast 3kB alternative to React with the same ES6 API.` and have about 11k stars in github.

**Comment by liumin1128** [comment]
I hope so

**Comment by blinkcat** [comment]
so, How did you solve this problem?
