### ISSUE TITLE
3.0.0 and UglifyJS

### ISSUE THREAD

**Issue by GuillaumeCisco** [zilverline/react-tap-event-plugin#110]
Interestingly with the last version 3.0.0, I get some errors when building my project for production by using Uglify.js.

I get an error like:
```
ERROR in main-9b29f1.js from UglifyJs
Unexpected token: punc ()) [./node_modules/react-tap-event-plugin/src/TapEventPlugin.js:58,0][main-9b29f1.js:23718,2]
```

Any idea about that?
I'm perplex....

**Comment by marcindabrowski** [comment]
I found the reason -  trailing function commas are used in code.

**Comment by elsbree** [comment]
Specifically, [this line](https://github.com/zilverline/react-tap-event-plugin/blob/master/src/TapEventPlugin.js#L69) contains a comma after the final argument of a function call.

**Comment by s0meone** [comment]
Removed the dangling commas in 3.0.1.
