### ISSUE TITLE
could you bump version to 0.2.x when requiring react 0.13?

### ISSUE THREAD

**Issue by totopia** [zilverline/react-tap-event-plugin#13]
react-tap-event-plugin@0.1.5 wants react@~0.13.x

Good to have support for 0.13 but this will break every build job currently using react 0.12. 
For example, if someone has `"react-tap-event-plugin": "~0.1.4"`, `npm install` will break build.

Since not all packages are up to speed with react 0.13 (it obviously has breaking changes, it's prob a good idea to bump version to 0.2 for 0.13+ and 0.1 for 0.12 stuff.

**Comment by s0meone** [comment]
You are absolutely right, totally forgot about that. I will now push a new version which supports both 0.12.x and 0.13.x.

**Comment by s0meone** [comment]
Version `0.1.6` is now on npm. Thanks for reporting.
