### ISSUE TITLE
Injecting plugin causes expensive layout recalculation on any touch event.

### ISSUE THREAD

**Issue by spicydonuts** [zilverline/react-tap-event-plugin#18]
This might be a problem with my setup, but at the very least there might be some people here who have some idea of what's going on.  I'm having some trouble identifying a performance issue on mobile.. maybe something on `touchstart` or `touchmove`, worse on larger pages.  But after profiling it doesn't seem to be javascript.. when I test in iOS 8 Safari it gives me large red blocks of "Recalculating Styles" with no other description.  The effect is smooth scrolling on small pages and awful 500+ms delayed scrolling on large pages, unless you continue scrolling through that 500ms, at which point it's smooth again until you put your finger back on the screen.

![Safari Timeline](https://cloud.githubusercontent.com/assets/715921/7460786/db49c52a-f262-11e4-8bd6-bfb27974daa8.png)

A few notes:
1. Seems to happen anywhere with real touch events -- I can't reproduce it on desktop Chrome where the timeline would be much more descriptive.
2. If I comment out `injectTapEventPlugin()` I no longer have any scroll lag.
3. I am calling React.render in many different places on this page, but I don't think that's an issue because commenting them out has no effect.

**Comment by s0meone** [comment]
I can't tell for sure without looking at your code, but it looks like a problem with your setup. We're using `onTouchTap` almost everywhere instead of `onClick`, on pretty long pages, and we're not seeing this issue.

**Comment by spicydonuts** [comment]
Still not sure what the issue was, but a CSS refactor helped.  I think it just made it unnoticeable.  Closing unless I find out more.
