### ISSUE TITLE
Cordova app (iOS) returning from background has incorrect timestamp for touch events

### ISSUE THREAD

**Issue by tomhicks-bsf** [zilverline/react-tap-event-plugin#19]
This is not the fault of this library, but seemingly a bug in UIWebView, but I thought it would be worth recording here (and possibly implementing a workaround in the plugin) to save someone else 2 days of their life.

In short, when a Cordova app returns from some particular background state in iOS, the timestamps on touch events are offset by the amount of time the app has been in the background. This means that the cancelling of mouse events doesn't work, because the time delta between last touch and current mouse event is like 3 minutes, instead of 300ms!

We figured out a workaround, which is to use ```Date.now()``` instead of ```nativeEvent.timeStamp``` when recording the ```lastTouchEvent``` time.

I've a few ideas about how this could be incorporated into this plugin:

1. Just always use ```Date.now()``` when recording the last touch timestamp
2. Make the tap event plugin into a function that takes a ```timeStampResolver``` as a function, and have a different version of the injector that passes in ```Date.now``` as the resolver for use in Cordova apps.
3. Make the timestamp getter into a public function so the ```TapEventPlugin``` can be monkey-patched on an app-by-app basis.

Thoughts @s0meone?

**Comment by s0meone** [comment]
This time delta only occurs for touch events? The following click event has a correct timestamp? 

It sounds like a bug indeed, when it's only for touch events. In that case, we could use `Date.now()` instead of `.timeStamp`.

**Comment by tomhicks-bsf** [comment]
Yeah you get a delta of like 2 minutes between the touch and the click!

**Comment by s0meone** [comment]
OK, weird. I'll try to confirm your issue later in a `UIWebView`. I just tried it in a `WKWebView` and I'm not seeing this issue. Maybe you could use something like https://github.com/Telerik-Verified-Plugins/WKWebView in the main time?

**Comment by tomhicks-bsf** [comment]
We've only tried it in UIWebView. We're not the only ones who've noticed the problem: http://stackoverflow.com/questions/26177087/ios-8-mobile-safari-wrong-timestamp-on-touch-events

It's a crazy bug!
