### ISSUE TITLE
Integrating the plugin

### ISSUE THREAD

**Issue by geekyme** [zilverline/react-tap-event-plugin#20]
Sorry I'm not sure if I'm doing it correctly but I included the following initialization code at the root of my client JS code:

<pre>

injectTapEventPlugin = require("react-tap-event-plugin");
injectTapEventPlugin()

</pre>

However I still encounter the 300ms lag. Am I suppose to bind onTouchTap on every single thing that is clickable? (Button, links, drop downs, tabs, etc)

**Comment by kellyrmilligan** [comment]
Yes bind to onTouchTap on anything you want to respond to a tap event on.

**Comment by geekyme** [comment]
@kellyrmilligan that seems like a great deal of work. FastClick seems to work just by initializing. So if I did not misunderstand you, that means my links <a> will all still have a 300ms lag?

**Comment by kellyrmilligan** [comment]
Yep although i tend not to worry about actual links in this case, only things that cause a Ui change.

**Comment by geekyme** [comment]
:S I wonder if there are other edge cases that  this repo handles. 

Have you tried http://stackoverflow.com/a/30316754 ? Just updated today

**Comment by geekyme** [comment]
the above answer solved the problem with fastclick
