### ISSUE TITLE
What about event's pageX or other event info

### ISSUE THREAD

**Issue by danyan** [zilverline/react-tap-event-plugin#23]

**Comment by s0meone** [comment]
Most of these values are not in the synthesized tap event.

You can get the values yourself from the `nativeEvent`, this will be a `mouseup` or a `touchend` event. Which is a [`MouseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) or a [`TouchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent).
