### ISSUE TITLE
Unnatural behavior when mouse moved more than 10px during click

### ISSUE THREAD

**Issue by fatfisz** [zilverline/react-tap-event-plugin#26]
I was clicking a bit to see how the UI of my little React project feels and noticed that `touchTap` wasn't firing half of the time. The cause seems to be this line:

``` js
if (isEndish(topLevelType) && distance < tapMoveThreshold) {
```

The distance check is performed for both touch events and  mouse events, but for mouse it is inconsistent with the natural behavior.
Let's say there is a 100px wide element; user pushes the mouse button on the left side of the element and releases it on the right side. The element should receive a click event - and also a touchTap event, I assume.

I can fix this if it is considered a valid issue.

**Comment by s0meone** [comment]
You are right, whenever a mouse event is happening, the tapMoveTreshold should probably be ignored.

**Comment by fatfisz** [comment]
I'll be looking at this in a couple of days then if my plans work out.

**Comment by fatfisz** [comment]
Closing this, as it's been inactive for quite some time. Sorry I didn't work on that as I wrote :( It seems that I moved on to other things since the time I opened this issue.
