### ISSUE TITLE
Loading w/ external React module

### ISSUE THREAD

**Issue by julieReitter** [zilverline/react-tap-event-plugin#28]
We're trying to use this library and Material UI in our app that is built with requirejs. We have a separate "react" module that's being loaded from a compiled version of React 0.13 and therefore we don't have access to the individual React modules that are needed for this patch to work. 

One attempt we've made is to use browserify to build a patched version of react-with-addons and then include that in our module dependencies. 
```coffee
React = require("../../node_modules/react/dist/react-with-addons");
React.initializeTouchEvents(true);

injector = require("../../node_modules/react-tap-event-plugin/src/injectTapEventPlugin");
injector();

module.exports = React;
``` 

Is there a more straightforward way to accomplish this? Also, this didn't work initially. We had to downgrade to React 13.0 and react-tap-event-plugin 1.6 to get it to work.

**Comment by zdychacek** [comment]
+1

**Comment by hartmamt** [comment]
Quick webpack example of how to patch react-with-addons with the tap events plugin.  This is required as far as I can tell if you want to use material-ui with react as an external dependency.
https://github.com/hartmamt/react-with-tap-events

**Comment by szarouski** [comment]
For anyone who'll come to here looking for solution, link from comment above will not work if you use React 14+ as support for initializeTouchEvents was removed.
