### ISSUE TITLE
tapMoveThreshold too low?

### ISSUE THREAD

**Issue by nickhudkins** [zilverline/react-tap-event-plugin#32]
Recently I added react-tap-event-plugin to a project, and was having users tell me that certain items were not registering taps (and instead causing :hover to be triggered) . So I dug in and found that what was happening was that they were relatively 'sloppy' tapping users. 

I noticed that the tapMoveThreshold is currently set to 10. (https://github.com/zilverline/react-tap-event-plugin/blob/master/src/TapEventPlugin.js#L49) Is 10 simply a number that felt right or does this correlate to something else and therefore must not change?

**Comment by s0meone** [comment]
This value was chosen by Facebook before we forked the tap plugin to fix it. 
I think the value 10 is chosen because after this threshold the view starts scrolling in most mobile browsers?

If you feel it's too low I would happily merge a pull request which makes this configurable.

**Comment by nhays** [comment]
Also having problems with this value. Getting a lot of false taps when scrolling. Manually lowering the threshold is working well, but would be nice to be able to configure this.

Will https://github.com/zilverline/react-tap-event-plugin/pull/63/commits/81c47dbc3fdb1bd13347a9ebc9ff614c998ef81d get merged?
