### ISSUE TITLE
Support React v0.14

### ISSUE THREAD

**Issue by oliviertassinari** [zilverline/react-tap-event-plugin#34]
The `react/lib/keyOf` module is no longer present inside react v0.14. He was moved to https://github.com/facebook/fbjs/blob/master/src/key-mirror/keyOf.js.

**Comment by goof03** [comment]
Need to remove React.initializeTouchEvents(true); in injectTapEventPlugin.js too

**Comment by oliviertassinari** [comment]
@goof03 I can't find `initializeTouchEvents` in the source code of this repository.

**Comment by goof03** [comment]
react-tap-event-plugin/src/injectTapEventPlugin.js

**Comment by oliviertassinari** [comment]
Indeed, I shouldn't trust the search engin of github. Thanks

**Comment by dmitry-zaets** [comment]
Guys, any updates so far?
Or probably any help needed?

**Comment by goof03** [comment]
@dmitry-zaets yes perhaps no sure to understand first is there a way to get your pull request in my project with npm ? your pull request make material-ui react 0.14 compatible no more need material-ui-io ?
