### ISSUE TITLE
Dependency React 0.14.0 is not yet released

### ISSUE THREAD

**Issue by pcx** [zilverline/react-tap-event-plugin#39]
npm ERR! peerinvalid Peer react-tap-event-plugin@0.2.0 wants react@^0.14.0-0

This plugin lists react 0.14.0-0 as a dependency. But the latest stable version still is 0.13.3. The release candidate has been out for a couple of weeks, but the stable 0.14.0 is not out yet. I wasn't able to install the plugin because of this.

**Comment by pcx** [comment]
This seems to be an issue with material-ui, which is being tracked here callemall/material-ui/issues/1712. Being new to npm I am not sure if this issue should be closed, because the error does show an unreleased version (react 0.14.0) is a dependency.

**Comment by skosch** [comment]
+1

**Comment by s0meone** [comment]
The plugin has a peerDependency on `^0.14.0-0` not `0.14.0` which currently satisfies with `0.14.0-rc1`. When you need compatibility with 0.13, you'll need the install an older version of the plugin.

See the included demo project for more info.

**Comment by pcx** [comment]
@s0meone Thanks for the clarification!
