### ISSUE TITLE
peer dependency on react-dom

### ISSUE THREAD

**Issue by mmckelvy** [zilverline/react-tap-event-plugin#48]
react-tap-event-plugin includes peer dependencies on react and react-dom.  The allowable react dependency includes `0.14` as well as `0.13` and `0.12`.  However, react-dom has a peer dependency on react `0.14` so if you are using react `0.13` and you install react-tap-event-plugin, you get a peer dependency error.

**Comment by otroboe** [comment]
Same error here.

Which version to use for react 0.13~ ?

**Comment by sambernard** [comment]
Having this issue as well

This is a breaking change for react < `0.14.0`.

**Comment by sambernard** [comment]
@otroboe @mmckelvy Solved it by locking to version `0.1.7`.

**Comment by mmckelvy** [comment]
Nice, thanks for the tip @sambernard.

**Comment by madjam002** [comment]
This was fixed in 8058164baffe576014c0931071edf8bc6daffa31
