### ISSUE TITLE
Add a way to detect if this plugin is injected

### ISSUE THREAD

**Issue by oliviertassinari** [zilverline/react-tap-event-plugin#57]
On the [material-ui](https://github.com/callemall/material-ui) repository, all the click/touch events depend on this plugin.
We have at least **one issue per week** of people how don't look at the [documentation](http://www.material-ui.com/#/get-started/installation) and complain that our component doesn't respond to click/touch interaction.

I'm looking for a way to throw a warning on all of our components if the plugin isn't injected. Any idea?
Thanks!

**Comment by s0meone** [comment]
Looking at the issue threads, it looks like you found a solution already? If you still need a solution, we could set some variable when injected, so you could check for the existence of that variable.

Let me know if you still need anything! :+1:

**Comment by oliviertassinari** [comment]
Indeed, we plan to move this plugin from the `peerDependencies` to the `depdencies` and make our components to inject it automatically. Thanks
