### ISSUE TITLE
bug of version 0.2.2

### ISSUE THREAD

**Issue by xiaosong** [zilverline/react-tap-event-plugin#59]
When I upgrade to 0.2.2, I got an error below:

```
Uncaught Invariant Violation: EventPluginRegistry: Cannot inject two different event plugins using the same name, `TapEventPlugin`.
```

I have two components require `react-tap-event-plugin`, each component have this line: `require('react-tap-event-plugin')()`

In version 0.2.1, it works fine but when I upgrade to 0.2.2, it did not work. Once I comment one of `require('react-tap-event-plugin')()`, it woks fine again.

**Comment by madjam002** [comment]
@xiaosong You're supposed to inject the tap event plugin once at the start of your application, not in each component.

If you're writing a library which provides components which require tap event plugin, you need to tell the consumer of your library to inject tap event plugin themselves.

Is that okay?

**Comment by xiaosong** [comment]
@madjam002 Why not your plugin determine whether tap event plugin is injected before inject?

**Comment by madjam002** [comment]
@xiaosong Take a look at https://github.com/callemall/material-ui/pull/3079#issuecomment-179124313

This is an ongoing discussion and will likely be fixed soon, I'll keep you posted. :+1:

**Comment by madjam002** [comment]
I'm going to close this in favour of #47, it's not as simple as just checking to see if the plugin has already been injected unfortunately.
