### ISSUE TITLE
Programmatically trigger a tap?

### ISSUE THREAD

**Issue by liorbrauer** [zilverline/react-tap-event-plugin#60]
Hi,

I have a use case where I need to manually call `$element.trigger('click')` (to get an `onClick={}` to work). However, if I have an `onTouchTap={}` property on my component, I'm not sure how to trigger it via JS.

I've tried `trigger('touch')`, `trigger('tap')`, `trigger('touchtap')` but non of them worked.

Is there a way to do so?

**Comment by madjam002** [comment]
@liorbrauer `trigger` is a jQuery method isn't it?

If you have something like `onTouchTap={this.handlePress}`, are you not able to just call `this.handlePress` instead?

**Comment by liorbrauer** [comment]
(Yes, sorry for not being more clear, I'm referring to jQuery's `trigger` method)

I'm not sure, the code I'm working on uses a mix of React and legacy backbone.js. Maybe I can send a reference of `this.handlePress` to the backbone code and have it called from there...

I just thought there might be a way to simulate a `tap` event via JS the same way it can be done with a `click` event.

**Comment by madjam002** [comment]
If you can call `handlePress`, that would be ideal.
Otherwise you might have some luck using `trigger` with `touchstart`, and `touchend` as `onTouchTap` uses these events to determine if it should be fired. You won't be able to trigger `onTouchTap` from jQuery as it's not a browser event.

**Comment by liorbrauer** [comment]
Just a quick update, I managed to solve it with sending a a bound reference (`this.handlePress.bind(this)`) to the backbone view and it works.

However, trying to trigger `touchstart` or `touchend` doesn't work. 

Thanks for the help @madjam002 :+1:

**Comment by madjam002** [comment]
Great, glad you managed to sort it out! :smile:

**Comment by elisei-timofte** [comment]
I have the same issue. My problem is that I don't have access to the `handlePress` method. I'm using a material-ui component and I want to trigger touchTap on mouseOver.

Any ideas? Thanks!

**Comment by garrettlancaster** [comment]
We have the same issue, but different use case. We're trying to integration test using capybara, so we don't have access to the actions.  Any thoughts?

**Comment by Zogoo** [comment]
Not related with this repository, 
Just want to share some information, because when when i start to learn about "tap" event this questions was top result of Google.

You can trigger TAP event with "dispatchEvent" function.
Tap is virtual event of JQuery not DOM event. It will collect following events with 300ms delay.

1. touchstart
2. touchend
3. mousedown
4. mouseup
5. click

Following example will help to trigger touch events.

`
      const viewportOffset = element.getBoundingClientRect();
      const elementCenterX = (viewportOffset.left + viewportOffset.width) / 2;
      const elementCenterY = (viewportOffset.top + viewportOffset.height) / 2;
      const touchObj = new Touch({
        target: element,
        clientX: elementCenterX,
        clientY: elementCenterY,
        radiusX: 10.5,
        radiusY: 10.5,
        rotationAngle: 10,
        force: 0,
        identifier: 0,
        pageX: elementCenterX,
        pageY: elementCenterY,
      });

      oEvent = new TouchEvent(eventName, {
        altKey: false,
        cancelable: true,
        bubbles: true,
        changedTouches: [touchObj],
        touches: [],
        targetTouches: [],
        shiftKey: true,
      });
`
