### ISSUE TITLE
Version bump for React 15?

### ISSUE THREAD

**Issue by stevewillard** [zilverline/react-tap-event-plugin#66]
Any chance you could release a new version of this, so I can try it out with the new React RC?

Thanks!

**Comment by marcelpanse** [comment]
I see the commit with the version bump, but it seems not to be release yet to npm, can you please do that?

Thanks!

**Comment by ciwolsey** [comment]
Just upgraded react 15 and noticed it's broken drop downs and such, could it be related to this package?

**Comment by kokarn** [comment]
It is, i've had the same issue. Updating to the latest version with `npm install https://github.com/zilverline/react-tap-event-plugin.git` fixes the issue.

**Comment by antoinerousseau** [comment]
thanks @kokarn !

looks like it's not yet in react 15.0, any idea when we can avoid using this plugin?

**Comment by nathanmarks** [comment]
Hey, can we get this published to `npm` ?

**Comment by juliengroch** [comment]
with last commit mui work well for me, we can have a npm release plz ?

**Comment by madjam002** [comment]
Sorry I have been on holiday, I'll message @s0meone and ask him about releasing. :smile:

**Comment by madjam002** [comment]
This has been done now thanks to @s0meone, so I'm closing this. Thanks everyone!
