### ISSUE TITLE
1.0.0 is not working with material-ui

### ISSUE THREAD

**Issue by jma7889** [zilverline/react-tap-event-plugin#67]
I updated to 1.0.0 today and my material-ui component is no longer responding to click anymore. Don't know who should I turn head to. No error message. I was using 0.2.2 before. Now I rolled back to it.

What did I miss here?

Jay

**Comment by madjam002** [comment]
What version of React are you using? 1.0.0 is meant to be used with React 15.

**Comment by jma7889** [comment]
I am using 0.14.x React. Thanks

**Comment by madjam002** [comment]
Yeah you'll need to stay on the old version until you upgrade to React 15
