### ISSUE TITLE
It seems that there is no react@15.0.0-0

### ISSUE THREAD

**Issue by shuaiyaotian** [zilverline/react-tap-event-plugin#69]
I got a "UNMET PEER DEPENDENCY" warning. The version of my react is 15.0.0. But I can't find react@15.0.0-0 as the configuration described in the package.json:
"peerDependencies": {
    "react": "^15.0.0-0"
}

**Comment by shuaiyaotian** [comment]
_npm info react_, I got 
{
    ...
     '0.14.8',
     '0.15.0-alpha.1',
     '15.0.0-rc.1',
     '15.0.0-rc.2',
     '15.0.0',
     '15.0.1',
     '15.0.2-alpha.1',
     '15.0.2-alpha.2',
     '15.0.2-alpha.3'
}

**Comment by madjam002** [comment]
What version of NPM are you running? `15.0.0-0` is a valid semver string as far as I'm aware.

I just ran npm install on my work mac and got this output (I'm using the slightly outdated 2.14.9):
```
npm WARN peerDependencies The peer dependency react@^15.0.0-0 included from react-tap-event-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
react@15.0.1 node_modules/react
├── object-assign@4.0.1
├── loose-envify@1.1.0 (js-tokens@1.0.3)
└── fbjs@0.8.1 (ua-parser-js@0.7.10, promise@7.1.1, babel-plugin-syntax-flow@6.5.0, core-js@1.2.6, isomorphic-fetch@2.2.1)

react-tap-event-plugin@1.0.0 node_modules/react-tap-event-plugin
└── fbjs@0.2.1 (whatwg-fetch@0.9.0, promise@7.1.1, core-js@1.2.6)
```

**Comment by shuaiyaotian** [comment]
Thank you for your replay. I went along a wrong way yesterday.
I imported material-ui@0.15.0-beta.2, got UNMET PEER DEPENDENCY react-tap-event-plugin@^1.0.0
My node is v5.10.1, npm is 3.8.3
Then I updated node to v6.0.0, npm to 3.8.6
I reinstalled, and got the save error.
At last I switched node to v4.2.4, everything was fine.

**Comment by hasssan** [comment]
Same error unmet dependency with node v5.8.0 and npm 3.7.3. 

Btw, I check `^15.0.0-0` in http://semver.npmjs.com/ and no result. But with `^15.0.0` it came out.

**Comment by hasssan** [comment]
My bad, ignore my previous comment. It's work with node v5.8.0 and npm 3.7.3.

My project use npm-shrinkwrap.json with react 0.14 that caused the problem.

**Comment by madjam002** [comment]
I'm going to close this for now, but I will re-open it if necessary 😊
