### ISSUE TITLE
onTouchTap's event.preventDefault() not working for click events

### ISSUE THREAD

**Issue by spicydonuts** [zilverline/react-tap-event-plugin#7]
This will (correctly) not redirect the page:
```js
<a href="/somewhere" onClick={(e) => e.preventDefault()}>Somewhere</a>
```

This will (correctly) not redirect the page *on a real touch event* (iOS Safari tap), but also (incorrectly) redirect the page on a click event (OS X Safari mouse click):
```js
<a href="/somewhere" onTouchTap={(e) => e.preventDefault()}>Somewhere</a>
```

This will work for both environments, but is not desirable:
```js
<a href="/somewhere" onClick={(e) => e.preventDefault()}
                     onTouchTap={(e) => e.preventDefault()}>Somewhere</a>
```

**Comment by s0meone** [comment]
Yes, I'm aware of this issue. I'm currently using the third option to work around this.

See https://github.com/facebook/react/issues/2061 for a more detailed explanation.

**Comment by doque** [comment]
Any update on this? This only seems to affect `<a>` elements with a valid `href`. Calling `e.preventDefault()` does not prevent browser navigation when clicking the link.
