### ISSUE TITLE
Tap invalid when use react with cdn

### ISSUE THREAD

**Issue by beiciye** [zilverline/react-tap-event-plugin#73]
Hi !

When I put React separated from the bundle , onTouchTap event does not fire.
If I React packaged bundle in , onTouchTap on the effective.
Could you help me ?

**Comment by madjam002** [comment]
I don't understand what you are trying to do...?

Are you trying to load React from a CDN and then package the rest of your app with webpack/browserify?

If so, I don't think it will work.

**Comment by beiciye** [comment]
yeah!  I have done all of these ,and it will not work.

**Comment by madjam002** [comment]
Yeah it's not designed to, you can't load React from a CDN and use tap event plugin.

**Comment by beiciye** [comment]
I think i should post my code 

/index.js
```
import injectTapEventPlugin from "react-tap-event-plugin";
injectTapEventPlugin({
    shouldRejectClick: function (lastTouchEventTimestamp, clickEventTimestamp) {
        return true;
    }
});

```

I use it like   `onTouchTap={this.handletest}`
something wrong?
