### ISSUE TITLE
Why tap event is still working on pc browser by mouse click?

### ISSUE THREAD

**Issue by g0ne150** [zilverline/react-tap-event-plugin#74]
I wonder why?

**Comment by madjam002** [comment]
`onTouchTap` also handles mouse events on desktop.

**Comment by g0ne150** [comment]
@madjam002 i just figure it out two mins ago.

**Comment by madjam002** [comment]
@g0ne150 What was the issue?

**Comment by g0ne150** [comment]
@madjam002 It doesn't reject click on desktop by default, so I wonder why `onTouchTap` is still fired by click on desktop

**Comment by madjam002** [comment]
`onTouchTap` will fire from a click event, that's by design.

**Comment by mrdulin** [comment]
same issue. Maybe the document should be more clear.
