### ISSUE TITLE
Unknown prop `onTouchTap` on <button> tag

### ISSUE THREAD

**Issue by lzbSun** [zilverline/react-tap-event-plugin#78]
react update 15.2.1 the 'onTouchTap' is not worked. Why?

**Comment by jaulz** [comment]
@lzbSun any solution for this? thanks!

**Comment by hyzhak** [comment]
how do you fix this warning? I got the same for: `react@15.4.1 and react-tap-event-plugin@2.0.1`

**Comment by WellerQu** [comment]
I got the same questions too. for react@15.4.1 and react-tap-event-plugin@2.0.1
