### ISSUE TITLE
Is this plugin still needed ?

### ISSUE THREAD

**Issue by Offirmo** [zilverline/react-tap-event-plugin#81]
I wonder whether I should use `onClick` or `onTouchTap` ?

The README mentions PRs and issues which are closed/merged.

React code seems to handle it natively: https://github.com/facebook/react/blob/54cbe2926249b0d8c1da17b6ecb19484cc409df1/src/renderers/dom/client/eventPlugins/TapEventPlugin.js#L143

Others say Apple fixed it on his side: https://www.reddit.com/r/reactjs/comments/4pe61k/why_do_we_need_reacttapeventplugin_in_our_projects/

So, is this plugin still needed if using latest React ? Should we use `onClick` or `onTouchTap` ?

Could the README be updated with latest infos on this regard ?

**Comment by pudgereyem** [comment]
I also wonder the same thing. I use `onClick` and it works fine in mobile Safari.
However, when the same website is bundles with Cordova, it still have the 300ms delay.

**Comment by HintikkaKimmo** [comment]
Just to make a comment on this, even though Chrome and Safari are now supporting onClick (tested it works at least on Safari ) there must be plenty of end user devices that cannot be or won't be updated to latest version or the respective mobile browsers. A Little bit like the IE issues on web development world.

**Comment by mahnunchik** [comment]
Any news?

**Comment by despire1119** [comment]
Waiting for official response.

**Comment by s0meone** [comment]
The TapEventPlugin in the React code base is not officially supported and is not enabled by default. Some browsers fixed the issue be cancelling the 300ms delay when building a web app, but not all users are able to upgrade.

So yes, when you want the same touch/click functionality with the latest React, you'll still need this plugin.

**Comment by s0meone** [comment]
Clarified the need for this plugin a bit more in the README.

Thanks.
