### ISSUE TITLE
Module errors

### ISSUE THREAD

**Issue by tthamel** [zilverline/react-tap-event-plugin#86]
ERROR in ./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginHub' in /Users/thamel10/Desktop/Fresh/ReatcDashB/jhbkh/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-37

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventConstants' in /Users/thamel10/Desktop/Fresh/ReatcDashB/jhbkh/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 22:21-56

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginUtils' in /Users/thamel10/Desktop/Fresh/ReatcDashB/jhbkh/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 23:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPropagators' in /Users/thamel10/Desktop/Fresh/ReatcDashB/jhbkh/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 24:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/SyntheticUIEvent' in /Users/thamel10/Desktop/Fresh/ReatcDashB/jhbkh/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 25:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/ViewportMetrics' in /Users/thamel10/Desktop/Fresh/ReatcDashB/jhbkh/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-58

what happened?

**Comment by s0meone** [comment]
React updated to 15.4. I've just released a new version of the plugin on npm (2.0.0). This version is compatible with React 15.4.

**Comment by tthamel** [comment]
but im not using react 15.4, is that a requirement now?

**Comment by tthamel** [comment]
one of my dependencies depends on version 1.0 of this.... so do all deps need to be updated and version 1 is no longer working?

**Comment by hozefaj** [comment]
@s0meone If you don't mind can you point out what change in react caused the issue?

**Comment by s0meone** [comment]
@hozefaj https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html

> However, there is a possibility that you imported private APIs from react/lib/*, or that a package you rely on might use them. We would like to remind you that this was never supported, and that your apps should not rely on internal APIs. The React internals will keep changing as we work to make React better.
