### ISSUE TITLE
Outdated path since react 15.4.0

### ISSUE THREAD

**Issue by dkwingsmt** [zilverline/react-tap-event-plugin#87]
A few modules that this plugin depends on seems to have been moved to new places in the latest react (≥15.4.0), which triggers the following and alike errors:
```
Module not found: Error: Cannot resolve module 'react/lib/EventPluginHub' in /path/to/my/propject/node_modules/react-tap-event-plugin/src
Module not found: Error: Cannot resolve module 'react/lib/EventConstants' in /path/to/my/propject/node_modules/react-tap-event-plugin/src
... (and so on)
```

Btw, is this plugin still necessary? Facebook have closed [#436](https://github.com/facebook/react/issues/436) and [#1170](https://github.com/facebook/react/pull/1170), but it seems they rejected them?

**Comment by s0meone** [comment]
I've just published a new version on npm (2.0.0) which fixes compatibility with React 15.4.

Yes, the plugin is still needed, see #81.

**Comment by dkwingsmt** [comment]
Thank you. And my apology for not checking closed issues before opening this one.

**Comment by dano-giftbit** [comment]
I'm not seeing 2.0.0 on [npm](https://www.npmjs.com/package/react-tap-event-plugin) ?

**Comment by s0meone** [comment]
```
$ npm view react-tap-event-plugin@latest version
2.0.0
```

The webpage on npmjs.org is cached probably. `npm install` will install the latest version.
