### ISSUE TITLE
Incompatible with React 15.4

### ISSUE THREAD

**Issue by esonderegger** [zilverline/react-tap-event-plugin#88]
react/lib/EventPluginHub is no longer available in React 15.4, which causes injectTapEventPlugin to fail at line 23.

**Comment by s0meone** [comment]
Please, check the closed issues first :) I've released a new version (2.0.0) of the plugin compatible with React 15.4.

**Comment by esonderegger** [comment]
I'm really sorry about that. I saw the release announcement for 15.4 earlier today, so figured it would be a new issue. In any event, thank you very much for making this!
