### ISSUE TITLE
react 15.4 compatibility 

### ISSUE THREAD

**Issue by bartvde** [zilverline/react-tap-event-plugin#89]
I see you edited the README to say it's not compatible with react 15.4

Are you working on a release that is compatible with 15.4, and if so, what is the timeline for this?

TIA for any insight.

**Comment by s0meone** [comment]
The latest and current version (2.0.0) is compatible with React v15.4.

**Comment by bartvde** [comment]
Ah thanks, I checked GitHub releases and didn't see a new release. But I see it on npmjs.com now.

**Comment by bartvde** [comment]
btw, it might make sense to release 1.0.1 as well with a more restricted react dependency? Otherwise people will not get a warning when using npm i?
