### ISSUE TITLE
Make it work with React > 0.12

### ISSUE THREAD

**Issue by iclanzan** [zilverline/react-tap-event-plugin#9]
I am using React 0.13-rc1 and this module fails to install because of unmet peer dependency on React 0.12.

**Comment by drejohnson** [comment]
I'm having the same issue

**Comment by spicydonuts** [comment]
Same here

**Comment by boyswan** [comment]
me too!

**Comment by locksmithdon** [comment]
Unfortunately, [material-ui](http://github.com/callemall/material-ui) takes a dependency on this repo. That repo is suffering from the same issue (callemall/material-ui#422). So either they drop the dependency (if they can) or wait. I'm already looking into doing a PR for the repo - I guess I can do the same for this one.

**Comment by kellyrmilligan** [comment]
is there any traction on this?

**Comment by spicydonuts** [comment]
I forked it and removed the peer dependency and haven't had issues yet, but I haven't tested much.  It was mostly so I could test other things until this is closed.

**Comment by alessandro-pezzato** [comment]
Same here

**Comment by BobertForever** [comment]
+1

**Comment by Jeweller-Tsai** [comment]
+1

**Comment by theunexpected1** [comment]
Could someone suggest a temporary fix?
Should I update all peerDependencies to 0.13.x, or 0.12.x?

**Comment by alessandro-pezzato** [comment]
why not >=0.12? At least temporarily... It seems to work.

Il giorno Gio 26 Mar 2015 13:54 Rahul Vagadiya <notifications@github.com>
ha scritto:

**Comment by s0meone** [comment]
Sorry for the delay, I'm currently not working on any React project :(

**Comment by zeskysee** [comment]
Thank you @s0meone for updating the plugin to support React ~0.13.x. :+1:

**Comment by theunexpected1** [comment]
Thanks @alessandro-pezzato & @s0meone. Resolved, appreciate the help. :+1:

**Comment by Jeweller-Tsai** [comment]
Thank you guys! :+1:

**Comment by Jeweller-Tsai** [comment]
Thank you guys! :+1:

**Comment by theunexpected1** [comment]
Since I am not committing the node_modules dir, the local changes to their package.json are naturally not commited; hence, travis ci fails. https://travis-ci.org/FipBlip/photare/jobs/56087682
Any suggestions? Should I start including the node_modules in git as last resort?

**Comment by s0meone** [comment]
@theunexpected1 You're locking your [React version at 0.12.x](https://github.com/FipBlip/photare/blob/master/package.json#L18). `react-router` needs 0.13.x. So either upgrade your React to version 0.13.x or downgrade `react-router`.

The latest `react-tap-event-plugin` on npm, requires either 0.12.x or 0.13.x.

**Comment by theunexpected1** [comment]
@s0meone thanks. I think u are looking at master, the issue is @ [ui-views](https://github.com/FipBlip/photare/blob/ui-views/package.json) where you can see I have upgraded `react` to ~0.13.1

**Comment by theunexpected1** [comment]
@s0meone seems it got [fixed](https://travis-ci.org/FipBlip/photare/jobs/56249802). No changes made from my end. Probably one of the libraries updated the `react` support. Thanks for helping, though.
