### ISSUE TITLE
Errors with 2.0.1

### ISSUE THREAD

**Issue by Strandedpirate** [zilverline/react-tap-event-plugin#91]
Started getting random errors after pulling the latest 2.0.1 release.

`Cannot resolve module 'react/lib/EventPluginHub'`

**Comment by yunderboy** [comment]
I too... :/

**Comment by olivierkastel** [comment]
I have the same issue too

**Comment by chipit24** [comment]
The release notes say:
> Use v.2.0.1 for React ^15.4.0. This version breaks compatibility with React < 15.4.

I'm using React 15.4.0 with react-tap-event-plugin 2.01 and have no issues.

**Comment by chipit24** [comment]
The release notes say:
> Use v.2.0.1 for React ^15.4.0. This version breaks compatibility with React < 15.4.

I'm using React 15.4.0 with react-tap-event-plugin 2.0.1 and have no issues.

**Comment by fc** [comment]
From the README.md... just double check your React version then pick one of the following:

Compatible with React > 0.14 && < 15.4:
```sh
$ npm i --save react-tap-event-plugin@1.0.0
```

Compatible with React <= 0.14:
```sh
$ npm i --save react-tap-event-plugin@0.2.2
```

**Comment by Strandedpirate** [comment]
I think the problem in my case is that `package.json` was configured like this:
`"react-tap-event-plugin": "^1.0.0"`

While I was installing another unrelated package (seneca.js) npm decided to pull down the latest version of this package `2.0.1` to screw with me..

I rolled back to 1.0.0 and removed the 'compatible with version' caret for this package in `package.json` and all is good again.
